### ISSUE TITLE
Using 'use' changes the current directory

### ISSUE THREAD

**Issue by tkob** [aliceml/aliceml#10]
Minor problem when using `use` to evaluate a source file in a subdirectory:

```
- OS.FileSys.getDir ();
### loaded signature from x-alice:/lib/system/OS
val it : string = "/tmp"
- use "sub/a.sml";
val it : unit = ()
### evaluating file /tmp/sub/a.sml
- OS.FileSys.getDir ();
val it : string = "/tmp/sub"
```

I don't know whether there is a rationale for this behavior, but a little bit confusing.

**Comment by doublec** [comment]
That is definitely confusing. I'm looking into it.

**Comment by doublec** [comment]
This appears to be related to how the [finally](http://www.ps.uni-saarland.de/alice/manual/sugar.html#finally) clause is handled. In [CoreTopLevel.aml](https://github.com/aliceml/aliceml-alice/blob/master/tools/toplevel/CoreToplevel.aml#L137-L141) there is a `finally` block that restores the directory after an `eval`. This isn't being called which results in the original directory not being restored.

Some testing at the REPL shows that `finally` should work:

    - 1 finally print "a\n";
    a
    val it : int = 1

But it seems to attach to the previous handler, rather than the original expression:

    - exception Foo
    - exception Bar
    - (1; raise Foo)
       handle Foo => (print "a\n"; 2)
       | e => (print "b\n"; 3)
       finally (print "c\n"; 4);
     a
     val it : int = 2
    
    - (1; raise Foo)
      handle Bar => (print "a\n"; 2) 
      | Foo => (print "b\n"; 3)
      finally (print "c\n"; 4);
    b
    c
    val it : int = 3
